<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Annium.Core.Mapper" Version="1.1.27" />
    <PackageVersion Include="Annium.Data.Operations" Version="1.1.27" />
    <PackageVersion Include="Annium.Data.Operations.Testing" Version="1.1.27" />
    <PackageVersion Include="Annium.Data.Tables" Version="1.1.27" />
    <PackageVersion Include="Annium.Execution.Background" Version="1.1.27" />
    <PackageVersion Include="Annium.Extensions.Pooling" Version="1.1.27" />
    <PackageVersion Include="Annium.Net.Http" Version="1.1.27" />
    <PackageVersion Include="Annium.Net.Servers.Web" Version="1.1.27" />
    <PackageVersion Include="Annium.Net.WebSockets" Version="1.1.27" />
    <PackageVersion Include="Annium.NodaTime.Extensions" Version="1.1.27" />
    <PackageVersion Include="Annium.Serialization.Abstractions" Version="1.1.27" />
    <PackageVersion Include="Annium.Serialization.Json" Version="1.1.27" />
    <PackageVersion Include="Annium.Testing" Version="1.1.27" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="NodaTime" Version="3.2.2" />
    <PackageVersion Include="xunit.v3" Version="3.2.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
